Fix: uncomment out

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,19 +48,18 @@ jobs:
         TAG=$(echo $result | cut -d ':' -f 2)
         echo "::set-output name=tag::$TAG"
 
-    # # フロントエンドのイメージタグを取得する
-    # # 一時的にコメントアウト
-    # - name: Get the latest Frontend image tag
-    #   id: get-frontend-tag
-    #   run: |
-    #     set -e
-    #     result=$(aws ecs describe-task-definition --task-definition tunetrail-frontend --query 'taskDefinition.containerDefinitions[0].image' --output text || echo "error")
-    #     if [ "$result" == "error" ]; then
-    #       echo "Failed to describe the task definition."
-    #       exit 1
-    #     fi
-    #     TAG=$(echo $result | cut -d ':' -f 2)
-    #     echo "::set-output name=tag::$TAG"
+    # フロントエンドのイメージタグを取得する
+    - name: Get the latest Frontend image tag
+      id: get-frontend-tag
+      run: |
+        set -e
+        result=$(aws ecs describe-task-definition --task-definition tunetrail-frontend --query 'taskDefinition.containerDefinitions[0].image' --output text || echo "error")
+        if [ "$result" == "error" ]; then
+          echo "Failed to describe the task definition."
+          exit 1
+        fi
+        TAG=$(echo $result | cut -d ':' -f 2)
+        echo "::set-output name=tag::$TAG"
 
   # デプロイジョブ
   deploy:
@@ -142,8 +141,7 @@ jobs:
     - name: Build, tag, and push Frontend image to Amazon ECR
       id: build-image-frontend
       # # フロントエンドディレクトリ以下に変更があった場合のみビルドする
-      # 一時的にコメントアウト
-      # if: contains(toJSON(github.event.commits.*.modified), 'frontend/')
+      if: contains(toJSON(github.event.commits.*.modified), 'frontend/')
       env:
         ECR_REGISTRY: ${{ steps.login-ecr-frontend.outputs.registry }}
         ECR_REPOSITORY: "tunetrail-frontend"
@@ -159,7 +157,6 @@ jobs:
     # フロントエンドのタグはコミットハッシュを使用する
     - name: Terraform Apply (Frontend only)
       # フロントエンドディレクトリ以下に変更があった場合のみデプロイする
-      # 一時的にコメントアウト
-      # if: contains(toJSON(github.event.commits.*.modified), 'frontend/')
+      if: contains(toJSON(github.event.commits.*.modified), 'frontend/')
       run: terraform apply -auto-approve -var "frontend_image_tag=${{ github.sha }}" -var "api_image_tag=${{ needs.prepare-deployment.outputs.api_image_tag }}" -var "db_password=${{ secrets.DB_PASSWORD }}"
       working-directory: ${{ env.TF_WORKING_DIR }}
